# Alternative GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=release
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),release)
  ping_pong_config = release

else ifeq ($(config),debug)
  ping_pong_config = debug

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := ping-pong

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

ping-pong:
ifneq (,$(ping_pong_config))
	@echo "==== Building ping-pong ($(ping_pong_config)) ===="
	@${MAKE} --no-print-directory -C . -f ping-pong.make config=$(ping_pong_config)
endif

clean:
	@${MAKE} --no-print-directory -C . -f ping-pong.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  release"
	@echo "  debug"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   ping-pong"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"